
CREATE TABLE sensores_regiao (
    id_sensor         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regiao            VARCHAR2(1) NOT NULL,
    temperatura       NUMBER(6,4),
    umidade           NUMBER(6,4),
    tipo_solo         VARCHAR2(20),
    inclinacao        VARCHAR2(20),
    chuva             VARCHAR2(20),
    vibracao          NUMBER(10,8),
    risco             NUMBER(10,8),
    nivel_risco       VARCHAR2(10)
);
